from sqlalchemy.orm import Session
from backend import models
from backend.signals.signal_registry import (is_operator_allowed, is_comparison_value_valid, get_signal_definition)
from backend.schemas import FraudRuleCreate

def generate_rule_key(rule_name: str) -> str:
    return (
        rule_name.strip()
        .lower()
        .replace(" ", "_")
    )

def get_rule(
    db: Session,
    rule_key: str,
) -> models.FraudRule | None:
    return (
        db.query(models.FraudRule)
        .filter(models.FraudRule.rule_key == rule_key)
        .first()
    )

def get_all_rules(
    db: Session,
    limit:int,
    offset:int
) -> list[models.FraudRule]:
    return (
        db.query(models.FraudRule)
        .order_by(models.FraudRule.rule_name.asc())
        .offset(offset)
        .limit(limit)   
        .all()
    )

## Helper function to validate rule parameters.
def validate_rule_configuration(
    signal_key: str,
    operator: str,
    comparison_value: int | float | bool,
    window_minutes: int | None,
) -> None:
    signal_definition = get_signal_definition(signal_key)

    if not is_operator_allowed(signal_key, operator):
        raise ValueError(
            f"Operator '{operator}' is not allowed "
            f"for signal '{signal_key}'."
        )

    if not is_comparison_value_valid(
        signal_key,
        comparison_value,
    ):
        raise ValueError(
            f"Comparison value '{comparison_value}' is not valid "
            f"for signal '{signal_key}'."
        )

    if (
        not signal_definition.uses_window
        and window_minutes is not None
    ):
        raise ValueError(
            f"Signal '{signal_key}' does not use a window."
        )

    if (
        signal_definition.uses_window
        and window_minutes is None
    ):
        raise ValueError(
            f"Signal '{signal_key}' requires window_minutes."
        )

def create_rule(
        db: Session,
        rule_data: FraudRuleCreate
) -> models.FraudRule:
    
    rule_key = generate_rule_key(rule_data.rule_name)

    existing_rule = (
        db.query(models.FraudRule)
        .filter(
            (models.FraudRule.rule_name == rule_data.rule_name)
            | (models.FraudRule.rule_key == rule_key)
        )
        .first()
    )

    if existing_rule:
        raise ValueError(
            "A rule with this name already exists."
        )

    validate_rule_configuration(
        signal_key=rule_data.signal_key,
        operator=rule_data.operator,
        comparison_value=rule_data.comparison_value,
        window_minutes=rule_data.window_minutes,
    )

    db_rule = models.FraudRule(
        rule_key = rule_key,
        **rule_data.model_dump()
    )

    db.add(db_rule)
    db.commit()
    db.refresh(db_rule)

    return db_rule

def update_rule(
    db: Session,
    rule: models.FraudRule,  #this rule is generated by get_rule function, which is called in the update_rule_with_key function in backend/routers/rules.py
    update_data: dict,
) -> models.FraudRule:
    
    # if enabled is not None:
    #     rule.enabled = enabled
    # if threshold_value is not None:
    #     rule.threshold_value = threshold_value
    # if score is not None:
    #     rule.score = score
    # if window_minutes is not None:
    #     rule.window_minutes = window_minutes
    #instead of above commented code, we can use setattr to update the attributes dynamically based on the keys in the update_data dictionary. This way, we can avoid writing multiple if statements for each attribute.

    effective_signal_key = update_data.get(
        "signal_key",
        rule.signal_key,
    )

    effective_operator = update_data.get(
        "operator",
        rule.operator,
    )

    effective_comparison_value = update_data.get(
        "comparison_value",
        rule.comparison_value,
    )

    effective_window_minutes = update_data.get(
        "window_minutes",
        rule.window_minutes,
    )

    if (
        effective_signal_key is not None
        and effective_operator is not None
        and effective_comparison_value is not None
    ):
        validate_rule_configuration(
            signal_key=effective_signal_key,
            operator=effective_operator,
            comparison_value=effective_comparison_value,
            window_minutes=effective_window_minutes,
        )

    for field, value in update_data.items():
        setattr(rule, field, value)

    db.commit()
    db.refresh(rule)
    return rule
