from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field
from typing import Literal

from pydantic import field_validator
from backend.signals.signal_registry import AVAILABLE_SIGNALS

RuleOperator = Literal[
    ">",
    ">=",
    "<",
    "<=",
    "==",
    "!=",
]

class TransactionCreate(BaseModel):
    transaction_id: str
    transaction_type: str | None = None
    transaction_status: str

    customer_id: str
    email: str

    card_fingerprint: str
    card_bin: str
    card_last_four: str
    payment_method: str
    card_country: str | None = None

    ip_address: str
    ip_country: str | None = None
    device_id: str
    user_agent: str | None = None
    session_id: str | None = None

    amount: float
    currency: str

class TransactionResponse(BaseModel):
    model_config = ConfigDict(
        from_attributes=True
    )

    id: int
    transaction_id: str
    transaction_type: str | None
    transaction_status: str

    customer_id: str
    email: str

    card_fingerprint: str
    card_bin: str
    card_last_four: str
    payment_method: str
    card_country: str | None

    ip_address: str
    ip_country: str | None
    device_id: str
    user_agent: str | None
    session_id: str | None

    amount: float
    currency: str
    created_at: datetime

class TransactionUpdate(BaseModel):
    amount: float | None = None
    currency: str | None = None

class RuleResult(BaseModel): #becoz dict have no validation and we want to validate the response from rules
    rule_name: str
    triggered: bool
    score: int
    reason: str

class FraudEvaluationResult(BaseModel):
    total_score: int
    decision: str
    rule_results: list[RuleResult]

class RuleEvaluationResponse(BaseModel):
    model_config = ConfigDict(
        from_attributes=True
    )

    id: int
    fraud_evaluation_id: int
    rule_name: str
    triggered: bool
    score: int
    reason: str

class FraudEvaluationResponse(BaseModel):
    model_config = ConfigDict(
        from_attributes=True
    )

    id: int
    transaction_db_id: int
    transaction: TransactionResponse
    total_score: int
    decision: str
    rule_evaluations: list[RuleEvaluationResponse]

class FraudRuleCreate(BaseModel):
    # rule_key: str #it will be generated by backend as it has to be unique
    rule_name: str
    signal_key: str 
    operator: RuleOperator
    comparison_value: int | float | bool 
    window_minutes: int | None = Field(default=None, gt=0)
    score: int = Field(ge=0)
    enabled: bool = True

    @field_validator("signal_key")
    @classmethod
    def validate_signal_key(cls, value: str) -> str:
        if value not in AVAILABLE_SIGNALS:
            raise ValueError(
                f"Unknown signal '{value}'. Refer to the Signal Registry."
            )

        return value

class FraudRuleResponse(BaseModel):
    model_config = ConfigDict(
        from_attributes=True
    )

    id: int
    rule_key: str
    rule_name: str
    signal_key: str | None
    operator: str | None
    enabled: bool
    threshold_value: int | None
    comparison_value: int | float | bool | None
    score: int
    window_minutes: int | None = None

class FraudRuleUpdate(BaseModel):
    signal_key: str | None = None
    operator: RuleOperator | None = None
    enabled: bool | None = None
    threshold_value: int | None = Field(default= None, gt= 0)
    comparison_value: int | float | bool | None = None
    score: int | None = Field(default= None, ge= 0)
    window_minutes: int | None = Field(default= None, gt= 0)

    @field_validator("signal_key")  # Validate signal_key against the Signal Registry before the request reaches the router.
    @classmethod
    def validate_signal_key(cls, value: str | None) -> str | None:
        if value is None:
            return value

        if value not in AVAILABLE_SIGNALS:
            raise ValueError(
                f"Unknown signal '{value}'. Refer to the Signal Registry."
            )

        return value

class DashboardSummary(BaseModel):
    total_transactions: int
    approved: int
    review: int
    rejected: int

class TransactionsOverTimeItem(BaseModel):
    date: str
    count: int

class SignalDefinitionResponse(BaseModel): #making response explicit.
    display_name: str                       #FastAPI doesn't have as strong an explicit declaration of what we promise to return.
    data_type: str
    category: str
    uses_window: bool
    description: str
    allowed_operators: list[str]