"""add dynamic rule fields

Revision ID: 4a66a5d15ff9
Revises: 91b49cce6b6b
Create Date: 2026-08-05 16:09:03.335200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a66a5d15ff9'
down_revision: Union[str, Sequence[str], None] = '91b49cce6b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fraud_rules', sa.Column('signal_key', sa.String(), nullable=True))
    op.add_column('fraud_rules', sa.Column('operator', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fraud_rules', 'operator')
    op.drop_column('fraud_rules', 'signal_key')
    # ### end Alembic commands ###
