"""make fraud rule threshold nullable

Revision ID: a5f64bb64da8
Revises: 09c0950d45cb
Create Date: 2026-08-07 18:09:23.479869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f64bb64da8'
down_revision: Union[str, Sequence[str], None] = '09c0950d45cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fraud_rules', 'threshold_value',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fraud_rules', 'threshold_value',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
