"""add comparison value to fraud rules

Revision ID: bc7fa9980ea2
Revises: 4a66a5d15ff9
Create Date: 2026-08-07 01:31:57.648815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7fa9980ea2'
down_revision: Union[str, Sequence[str], None] = '4a66a5d15ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fraud_rules', sa.Column('comparison_value', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fraud_rules', 'comparison_value')
    # ### end Alembic commands ###
